dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=39.0.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - ffmpeg=4.3
  - fftw=3.3.9
  - filelock=3.9.0
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - huggingface_hub=0.10.1
  - idna=3.4
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - joblib=1.1.1
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.7.1.12
  - libcurand=10.3.3.129
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - nettle=3.7.3
  - nltk=3.7
  - numexpr=2.8.4
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openh264=2.1.1
  - openssl=1.1.1v
  - packaging=22.0
  - pandas=1.3.5
  - pillow=9.4.0
  - pip=22.3.1
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.7.16
  - python-dateutil=2.8.2
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2022.7
  - pyyaml=6.0
  - readline=8.2
  - regex=2022.7.9
  - requests=2.28.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.41.2
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tokenizers=0.11.4
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tqdm=4.64.1
  - transformers=4.24.0
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - urllib3=1.26.14
  - wheel=0.38.4
  - xz=5.4.2
  - yaml=0.2.5
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
